# 텐서 (Tensor)

텐서(Tenser)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조 입니다. Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)합니다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 *NumPy*의 ndarray와 유사합니다. 실제로 텐서와 NumPy배열(array)은 종종 동일한 내부(underly)메모리를 공유할 수 있어 데이터를 복사할 필요가 없습니다.(*Numpy 변환(Bridge)*) 텐서는 또한 자동 미분(automatic differentiation)에 최적화 되어 있습니다.ndarray에 익숙하다면 Tensor API를 바로 사용할 수 있습니다.

In [1]:
import torch
import numpy as np

## 텐서(Tensor) 초기화

텐서는 여러가지 방법으로 초기화 할 수 있습니다.

## 데이터로부터 직접(Directly) 생성하기

데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형(data type)은 자동으로 유추합니다.

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## Numpy 배열로부터 생성하기

텐서는 NumPy배열로 생성할 수 있습니다. (그 반대도 가능합니다)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

## 다른 텐서로부터 생성하기

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1563, 0.7534],
        [0.6269, 0.6451]]) 


## 무작위(Random) 또는 상수(Constant) 값을 사용하기

`shape`는 텐서의 차원(dimension)을 나타내는 튜플(tuple)입니다.

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9312, 0.3207, 0.2003],
        [0.2806, 0.8185, 0.2184]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성(Attribute)

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서 연산(Operation)

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학계산, 선형대수, 임의 샘플링(random sampling)등, 100가지 이상의 텐서 연산을 [여기](https://pytorch.org/docs/stable/torch.html)에서 확인할 수 있습니다. 각 연산은 CPU나 GPU같은 장치(device)에서 실행할 수 있습니다. 기본적으로 텐서는 CPU에서 생성되며, `.to`메소드를 사용하여 명시적으로 GPU로 옮길 수 있습니다. 장치들 간에 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 발생합니다.

In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

목록에서 몇몇 연산들을 시도 합니다.

### NumPy식의 표준 인덱싱과 슬라이싱

In [8]:
tensor = torch.ones(4, 4)

print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1]=0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 텐서 합치기

`torch.cat`을 사용하여 주어진 차원에 따라 일련의 텐서를 연결(concatenate)합니다. `torch.cat`과 Python의 슬라이싱(slicing)을 함께 사용하면, 쉽게 텐서를 분할(half)하거나 연결(concatenate)할 수 있습니다.

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### 산술 연산(Arithmetic operations)

In [10]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다.
# `tensor.T` 는 텐서의 전치(transpose)를 반환합니다.

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# 요소별 곱(element-wise product)을 계산합니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 단일 요소(single-element) 텐서

텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, `item()`을 사용하여 Python 숫자 값으로 변환할 수 있습니다.

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### In-place 연산

연산 결과를 피연산자(operand)에 저장하는 연산(in-place operation)은 `_`를 접미사(suffix)로 갖습니다. 예: `x.copy_(y)`, `x.t_()`는 `x`가 변경됨을 나타냅니다.

In [12]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


NumPy 변환 (Bridge)

CPU 상의 모든 텐서는 NumPy로 변환할 수 있고, 반대로 NumPy 배열은 텐서로 변환할 수 있습니다.

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy배열에 반영되고, 그 반대의 경우도 마찬가지입니다.

In [14]:
t.add_(1)
print(f'numpy array: {n}')
print(f'tensor: {t}')

numpy array: [2. 2. 2. 2. 2.]
tensor: tensor([2., 2., 2., 2., 2.])


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"numpy array: {n}")
print(f"tensor: {t}")

numpy array: [2. 2. 2. 2. 2.]
tensor: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
